# fly.toml app configuration file
# See https://fly.io/docs/reference/configuration/

app = 'agent-core-autumn-pond-8052'
primary_region = 'phx'
kill_signal = 'SIGINT'
kill_timeout = '5s'

[build]
  dockerfile = 'Dockerfile'

[env]
  PORT = '8000'
  REDIS_DB = '0'
  ARXIV_MAX_RESULTS = '5'
  SCHOLAR_MAX_RESULTS = '5'
  MEMORY_WINDOW_SIZE = '20'
  CONTEXT_WINDOW_SIZE = '4'
  ENABLE_GPU = 'false'
  LOG_LEVEL = 'INFO'
  LLM_MODEL = 'mistralai/mistral-medium-3.1'
  LLM_MAX_TOKENS = '2048'
  LLM_TEMPERATURE = '0.7'

[http_service]
  internal_port = 8000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

[[services]]
  protocol = 'tcp'
  internal_port = 8001
  auto_stop_machines = false
  auto_start_machines = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']
  
  [[services.ports]]
    port = 8001
    handlers = ['tls']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
