version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: agent-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  agent:
    build: .
    container_name: agent-core
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    stdin_open: true
    tty: true
    volumes:
      - ./knowledge_base:/app/knowledge_base
      - ./logs:/app/logs
    command: python agent_chat.py

  worker:
    build: .
    container_name: agent-worker
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy
    volumes:
      - ./knowledge_base:/app/knowledge_base
      - ./research_papers:/app/research_papers
    command: python -m rq worker research default --url redis://redis:6379

volumes:
  redis_data:
    driver: local